services:
  ai-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-proxy
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
